#cloud-config
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - git
  - ufw
  - ca-certificates
  - gnupg
  - curl
  - build-essential
  - rsync
  - micro
  - fzf
  - eza
  - exa
  - bat
  - xorriso
  - qemu
  - qemu-utils
  - qemu-system

runcmd:
  - ufw allow ssh
  - ufw --force enable
