#cloud-config
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - git
  - rsync
  - micro
  - fzf
  - eza
  - exa
  - bat
  - xorriso
  - qemu
  - qemu-utils
  - qemu-system
